# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# syntax : https://github.com/Shopify/liquid/wiki/Liquid-for-Designers

# Gems
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Site settings
title: Elie | Capture you. Camera for you.
email: your@elie.camera
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://elie.camera"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Appstore
appstore_id : "1051585862"

# External links
facebook : /facebook
twitter : http://twitter.com/elie_cam
vimeo : https://vimeo.com/user46402004/videos

# i18n
# 3166-1 : https://en.wikipedia.org/wiki/ISO_3166-1
# 0x0404 zh-TW Chinese (Taiwan)                     0x7C04 zh-CHT Chinese (Traditional)
# 0x0804 zh-CN Chinese (People's Republic of China) 0x0004 zh-CHS Chinese (Simplified)
# 0x0C04 zh-HK Chinese (Hong Kong S.A.R.)           0x7C04 zh-CHT Chinese (Traditional)
# 0x1004 zh-SG Chinese (Singapore)                  0x0004 zh-CHS Chinese (Simplified)
# 0x1404 zh-MO Chinese (Macau S.A.R.)               0x7C04 zh-CHT Chinese (Traditional)
# follwing : https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
langs:
    en :
        countries : [US, GB, AU] # iso3166-1 alpha 2
        label : English
        path : "/"
    de :
        countries : [DE]
        label : Deutsch
        path : "/de"
    fr :
        countries : [FR, CA]
        label : Français
        path : "/fr"
    ja :
        countries : [JP]
        label : 日本語
        path : "/ja"
    zh-Hans :
        countries : [CN, SG]
        label : 中文
        path : "/zh-Hans"
    zh-Hant :
        countries : [HK, TW]
        label : 中文
        path : "/zh-Hant"
# - Tiếng Việt : vn
# - Italiano : it
# - العربية : sa
# - Čeština : cz
# - Bahasa Indonesia : id
# - Español : es
# - Русский : ru
# - Türkçe : tr
# - Română : ro
# - Polski : pl
# - Nederlands (Nederland) : nl
# - Magyar : hu
# - हिंदी : in
# - 한국어 : kr
# - Українською : ua
# - Ελληνικά : gr
