# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# syntax :
# https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
# http://cheat.markdunkley.com/
# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
# http://www.rubydoc.info/github/mojombo/jekyll/Jekyll

# github-pages status
# https://github.com/github/pages-gem/blob/master/lib/github-pages.rb
# https://pages.github.com/versions/

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from

highlighter: rouge
# Site settings
email: your@elie.camera
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://elie.camera"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Internal
deeplink_url_open : "eliecam://open"

# Appstore
appstore_version : "1.0"
appstore_id : "1076217298"
appstore_url : "http://itunes.apple.com/app/apple-store/id1076217298?pt=2020888&ct=badge_151230&mt=8"
appstore_name : "Elie - Your next mobile photography assistant, Automatic selfie camera"
appids:
    com.stells.eliew:
        name: Elie - Free
    com.stells.elie:
        name: Elie

# Business
page_title_head : "Elie | "
presskit_url : http://github.com/iamelie/elie-presskit/archive/master.zip
marketing_main_desc : "An intelligent, automatic photographing camera without a shutter button."
marketing_sub_desc : "When you are almost finished posing, Elie will take a picture of you."
marketing_keywords : "Mobile photography,Elie,Elie app,Elie Camera,iPhoneography,Elie for iPhone,Elie for iOS,iPhone photography,StellarStep,Buttonless camera,Messenger share,Filter effects"

# External links
facebook : /facebook
instagram: https://www.instagram.com/your_elie
twitter : http://twitter.com/elie_cam
vimeo : https://vimeo.com/user46402004/videos

# i18n
# 3166-1 : https://en.wikipedia.org/wiki/ISO_3166-1
# 0x0404 zh-TW Chinese (Taiwan)                     0x7C04 zh-CHT Chinese (Traditional)
# 0x0804 zh-CN Chinese (People's Republic of China) 0x0004 zh-CHS Chinese (Simplified)
# 0x0C04 zh-HK Chinese (Hong Kong S.A.R.)           0x7C04 zh-CHT Chinese (Traditional)
# 0x1004 zh-SG Chinese (Singapore)                  0x0004 zh-CHS Chinese (Simplified)
# 0x1404 zh-MO Chinese (Macau S.A.R.)               0x7C04 zh-CHT Chinese (Traditional)
# follwing : https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
baselang: en
langs:
    en :
        countries : [US, GB, AU] # iso3166-1 alpha 2
        label : English
        path : "/en"
        root : true
    de :
        countries : [DE]
        label : Deutsch
        path : "/de"
    fr :
        countries : [FR, CA]
        label : Français
        path : "/fr"
    ja :
        countries : [JP]
        label : 日本語
        path : "/ja"
    zh-Hans :
        countries : [CN, SG]
        label : 中文
        path : "/zh-Hans"
    zh-Hant :
        countries : [HK, TW]
        label : 中文
        path : "/zh-Hant"
    ko :
        countries : [KR]
        label : 한국어
        path : "/ko"
# - Tiếng Việt : vn
# - Italiano : it
# - العربية : sa
# - Čeština : cz
# - Bahasa Indonesia : id
# - Español : es
# - Русский : ru
# - Türkçe : tr
# - Română : ro
# - Polski : pl
# - Nederlands (Nederland) : nl
# - Magyar : hu
# - हिंदी : in
# - 한국어 : kr
# - Українською : ua
# - Ελληνικά : gr
